all:
	g++ minor.cpp -o minor.out -std=c++14
	g++ simple_assignment4.cpp -o simple.out -std=c++14
	g++ final_assignment4.cpp -o final.out -std=c++14
run:
	@echo "Minor Output - "
	./minor.out $(input) 10 2
	@echo ""
	@echo "Simple Assignment 4 Output - "
	./simple.out $(input) 10 2
	@echo ""
	@echo "Final Assignment 4 Output - "
	./final.out $(input) 10 2
clean:
	rm *.out