all:
	g++ assignment4.cpp -o a4.out -std=c++14
	g++ minor.cpp -o minor.out -std=c++14
	g++ strong_assignment4.cpp -o s.out -std=c++14
run:
	@echo "Minor Output - "
	./minor.out $(input) 10 2
	@echo ""
	@echo "Assignment 4 Output - "
	./a4.out $(input) 10 2
	@echo ""
	@echo "Strong Assignment 4 Output - "
	./s.out $(input) 10 2
clean:
	rm a.out