all:
	g++ method2.cpp -o a5.out -std=c++14
	g++ final_assignment4.cpp -o a4.out -std=c++14
run:
	@echo "Final Assignment 5 Output - "
	./a5.out 3 15000 t7 t8 t9 10 2
	@echo "File1 Output - "
	./a4.out t7 10 2
	@echo "File2 Output - "
	./a4.out t8 10 2
	@echo "File3 Output - "
	./a4.out t9 10 2
clean:
	rm *.out